### ISSUE TITLE
NO_PROXY, HTTP_PROXY, ALL_PROXY support

### ISSUE THREAD

**Issue by tracker1** [gajus/xfetch#5]
Would be nice to see `NO_PROXY` support in addition to `HTTPS_PROXY` and `ALL_PROXY`.

Not that they're really all necessary since are usually the same, and ALL_PROXY isn't generally set in practice... `NO_PROXY` would be a really nice add though.

**Comment by gajus** [comment]
> The NO_PROXY environment variable specifies URLs that should be excluded from proxying (on servers that should be contacted directly). This should be a comma-separated list of hostnames, domain names, or a mixture of both. Asterisks can be used as wildcards, but other clients may not support that.

– https://www.gnu.org/software/emacs/manual/html_node/url/Proxies.html

Makes sense. Can you raise a PR?

Otherwise, I will release this in couple of days.

**Comment by tracker1** [comment]
If I get time, I'll look into a PR...

Question, should the env be processed once, or per request?  Not that it's a huge overhead, but could have an effect on environments making a lot of outbound connections.

note: will probably use `URL`[0] to parse the protocol/hostname in order to compare to the NO_PROXY env.  In conjunction with `wildcard`[1]...  

    process.env.NO_PROXY
        .split(',')
        .map(m => m.trim().replace(/\.$/,'.*').replace(/^\./, '*.'))
        .filter(m => m)

[0] https://nodejs.org/api/url.html
[1] https://www.npmjs.com/package/wildcard

Aside, thinking this detection might be something suitable for a separate node module, that could be reused... since the detection of `getSystemProxyForUrl(url: string) : string?` might be something worthwhile and reusable for other abstractions.

**Comment by gajus** [comment]
> Question, should the env be processed once, or per request? Not that it's a huge overhead, but could have an effect on environments making a lot of outbound connections.

Once.

ENV variable cannot change during the execution of a program (unless you literally override `process.env`, something I have not seen anyone doing).

> Aside, thinking this detection might be something suitable for a separate node module, that could be reused... since the detection of getSystemProxyForUrl(url: string) : string? might be something worthwhile and reusable for other abstractions.

Sure. I am Okay with this.
